language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build
script:
- docker-compose run web typesafety --review --verbose
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: 4xg4QmFhLWyFtyucv9pmbdHEU14F3NTiQiOWvCfEsiOp1WOeTLAgLDDJKBywbnLVlOOq2QlxsJwofxhRSlE+2ikjygE1/v9kJGq7IIJn7+DL2ljifKQN/uEZM5A6+ssRNHJOCpBBJxMJBXUjIUrahFN7y1I3LZw24cNgXoAknsdKN97dZ1tMq4710hzYZ1j2fp2c6Q+9V/nVg75nqoiiuJyph5XapsiIvG0ypCLkiZtj9HrTjlZQk6ej+s5u8U5WLPkdlFCe/tamdoaN0w6dGegXpbFZo1WFc9jYJFFnmyO8NktKCsXJBMr3QPh0fFvi0fyJy8ZmLbHhltxfD0krPPEiPH7MtAD8x4aTPFcaFIVa8/r6rGn4kVl1Dw1VpoZXjwUZlepIHtumYpCP7OgSK02+WeS1BSB380GRcJKXtMuXmplrbWShWi5HarR/Z5gF2kdNOFsTcn3axYLn5YbBCLfl29Oa+U+pyDRDDrYh3EeM4kpDbW5YBSZgAEK8eH7Hy2p/rHTV2HxkboM9z6vaUchorixe7+5U40kWf4ac9zsa8k0MzOI73Y35jf7ARyBKlh1+2GLr6IF50TrXUCEfHHu7mFG8g0Rlv+vRLyigyw57e1mKkKJ0eoTHieMnB5cbS5LgubKp2h955A4z9rsgltqoGFbGFPVTE5SvcIk61LU=
  - secure: ToEI+gYRAVR0MwiAFJcZU5Y3g/c6Zf86mHuSl3I+SQGm3sQJgY/VkdnB3LjeoIy5ece1AhuWZsQAjL7Cp51NuPRHlwDJH1SQ2lbf++Ymv5XrJwngw5OmzrzV/UtEb9ERRgymc27QJrjlorK7Fu6oMXjy+lBL2nc0uiBrIEiK9bPCz9jQSML5vjPy1chIhjCGXt1k6jMLECeCc5xb59mpLU0JmqRico1jY28wtCBR8LrvrFTGrkEmM9d+XEH3tiaIoG8154Et7q+ur6hJ0p1AWIx1iLXOY6jOUjA4geXzfaAzkTBNpqpLuafj2wmePxqtdX34DynKw6vKkTFl7WwyizxBv7ufYV6LutPvOpr80DGa8P+UOzTRltN4q2WBsA+aDQT80TT1iXNEomxZk37o76ieF9+szygoj7JKHbLOh0yHE4COW+GQmMyvGlxcjhLj0Dec8iwxk2XN0X9pm9g9sK9i8vavnww5cjV2Iiw/+Tw2EusIaNuC5bcFRsewNq9LLzaFetG2h/rGVTExHiJ/Aiat1xW03ozalk9fc0mLVgYM3Yr4JoNFM+lw6rcIfYI16zED2no5bt9tjaFrjwiDXXE5p6dw621K4I8+OfWq0rOEex3Pa2/aEt5mwvv4D19xfXfqCB87suPq2ZHHmbR2yF5TpAUx3ECe6PYt+04yvy4=
  - secure: IFVcaLAaKIYVj3Av1EQz0e3iJrs/Y/4PEEodPSLqDQMtO7fWUwkRaw+m7DOFVMFVGui3TZaxDKpAGP3BeS7Bsw4/eqOEGsZXtNlsirSQ+RlvjRwHcyyW+TdbZOKA0N2cBuKrNnQILTcOqy35nFchClQRNjNR6teQct/WOo9x7enSnfPHZla8vQnjjumycOPok6c2mU0orp+O6Gxn04bgOYyZk0QJbnXUJIxxEqwyW5rB/EXwxP0m3VpKnNRJl2bkwqe8iZiE6w0lD/HlApafPv5j/gkrvZnx6v4W8/nlRlvrD/Q36RNnOGqilcToiRWRwWCSSbebfdp0KyTe10VGYhRO1IEV0DikZjsAG2mBTfUb/YlxERGjwn2uNKd6M11ozJgHFiygM6kPu7y25gqaVt3zR+Hq3yjKRBWIjxvHjc5cWotwG9TkXiHiWrNPHuo0Nc8Zue2tQWhwjah/cqwQT6iwNZZ0Y52g3VmEksUXSz7MhI5k6kmqbNHkWz8Bzc2ruDE+UjHhwlbIhYhJ9L6Q8nVXHrJqa31Uoakjny2D8elCqcDXJvacSTsMHoce3MtvubWXXsGZZ9UKrg33HicEP+DlmjQUR0H5tXEYRD1JiRv+2qJIW3YCDUnxiCwcsrpB2qOPPoGcpAQCXtcRXdtiz59EUv89C2/LsrbmLB5T5Ig=
